name: Tarea Automatizada de Pruebas Unitarias

env:
  SONAR_ORG: 'jesushuallpaepis3'
  SONAR_PROJECT: 'jesushuallpaepis3_sosaa'

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo_mysql, xdebug

    - name: Install Composer dependencies
      run: composer install

    - name: Give execute permission to PHPUnit
      run: chmod +x vendor/bin/phpunit

    - name: Run PHPUnit tests
      run: php -dxdebug.mode=coverage vendor/bin/phpunit --coverage-html coverage-report

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=${{ env.SONAR_PROJECT }}
          -Dsonar.organization=${{ env.SONAR_ORG }}
          -Dsonar.php.coverage.reportPaths=coverage.xml

    - name: Upload PHPUnit test report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: junit-report
        path: junit.xml

    - name: Upload PHPUnit coverage report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml

    - name: Create coverage directory
      run: mkdir -p coverage

    - name: List coverage directory
      run: ls -R coverage-report

    - name: Deploy PHPUnit coverage report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PAT_TOKEN }}
        publish_branch: unittests
        publish_dir: coverage-report
        allow_empty_commit: false
        keep_files: false
        force_orphan: false
        enable_jekyll: false
        exclude_assets: .github
      env:
        COMPOSER_PROCESS_TIMEOUT: 0
        COMPOSER_NO_INTERACTION: 1
        COMPOSER_NO_AUDIT: 1
